# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from editdetail import Ui_editdetails

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):

    def close(self):
         import sys
         sys.exit(0)
         
    def openwindow(self):
        self.editdetails=QtGui.QMainWindow()
        self.ui=Ui_editdetails()
        self.ui.setupUi(self.editdetails)
        self.editdetails.show()
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(963, 745)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(290, 100, 531, 601))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.detailstab = QtGui.QWidget()
        self.detailstab.setObjectName(_fromUtf8("detailstab"))
        self.entername = QtGui.QLabel(self.detailstab)
        self.entername.setGeometry(QtCore.QRect(120, 130, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entername.setFont(font)
        self.entername.setObjectName(_fromUtf8("entername"))
        self.fname = QtGui.QLabel(self.detailstab)
        self.fname.setGeometry(QtCore.QRect(230, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fname.setFont(font)
        self.fname.setObjectName(_fromUtf8("fname"))
        self.entergen = QtGui.QLabel(self.detailstab)
        self.entergen.setGeometry(QtCore.QRect(120, 160, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entergen.setFont(font)
        self.entergen.setObjectName(_fromUtf8("entergen"))
        self.enterdob = QtGui.QLabel(self.detailstab)
        self.enterdob.setGeometry(QtCore.QRect(120, 190, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enterdob.setFont(font)
        self.enterdob.setObjectName(_fromUtf8("enterdob"))
        self.enteradd = QtGui.QLabel(self.detailstab)
        self.enteradd.setGeometry(QtCore.QRect(120, 220, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enteradd.setFont(font)
        self.enteradd.setObjectName(_fromUtf8("enteradd"))
        self.enteradhar = QtGui.QLabel(self.detailstab)
        self.enteradhar.setGeometry(QtCore.QRect(120, 250, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enteradhar.setFont(font)
        self.enteradhar.setObjectName(_fromUtf8("enteradhar"))
        self.entermobile = QtGui.QLabel(self.detailstab)
        self.entermobile.setGeometry(QtCore.QRect(120, 280, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entermobile.setFont(font)
        self.entermobile.setObjectName(_fromUtf8("entermobile"))
        self.lname = QtGui.QLabel(self.detailstab)
        self.lname.setGeometry(QtCore.QRect(310, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lname.setFont(font)
        self.lname.setObjectName(_fromUtf8("lname"))
        self.gender = QtGui.QLabel(self.detailstab)
        self.gender.setGeometry(QtCore.QRect(230, 160, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gender.setFont(font)
        self.gender.setObjectName(_fromUtf8("gender"))
        self.dob = QtGui.QLabel(self.detailstab)
        self.dob.setGeometry(QtCore.QRect(230, 190, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dob.setFont(font)
        self.dob.setObjectName(_fromUtf8("dob"))
        self.add = QtGui.QLabel(self.detailstab)
        self.add.setGeometry(QtCore.QRect(230, 220, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add.setFont(font)
        self.add.setObjectName(_fromUtf8("add"))
        self.adhar = QtGui.QLabel(self.detailstab)
        self.adhar.setGeometry(QtCore.QRect(230, 250, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.adhar.setFont(font)
        self.adhar.setObjectName(_fromUtf8("adhar"))
        self.mobile = QtGui.QLabel(self.detailstab)
        self.mobile.setGeometry(QtCore.QRect(230, 280, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mobile.setFont(font)
        self.mobile.setObjectName(_fromUtf8("mobile"))
        self.label = QtGui.QLabel(self.detailstab)
        self.label.setGeometry(QtCore.QRect(130, 60, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.logout_btn = QtGui.QPushButton(self.detailstab)
        ###############################################

        self.logout_btn.clicked.connect(self.close)

        ###################################################
        self.logout_btn.setGeometry(QtCore.QRect(240, 350, 81, 31))
        self.logout_btn.setObjectName(_fromUtf8("logout_btn"))
        self.editdetails_btn = QtGui.QPushButton(self.detailstab)
        ###############################################
        self.editdetails_btn.clicked.connect(self.openwindow)

        ##############################################
        self.editdetails_btn.setGeometry(QtCore.QRect(120, 350, 91, 31))
        self.editdetails_btn.setObjectName(_fromUtf8("editdetails_btn"))
        self.tabWidget.addTab(self.detailstab, _fromUtf8(""))
        self.buyticket_tab = QtGui.QWidget()
        self.buyticket_tab.setObjectName(_fromUtf8("buyticket_tab"))
        self.fromlabel = QtGui.QLabel(self.buyticket_tab)
        self.fromlabel.setGeometry(QtCore.QRect(130, 110, 53, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fromlabel.setFont(font)
        self.fromlabel.setObjectName(_fromUtf8("fromlabel"))
        self.tolabel = QtGui.QLabel(self.buyticket_tab)
        self.tolabel.setGeometry(QtCore.QRect(130, 140, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tolabel.setFont(font)
        self.tolabel.setObjectName(_fromUtf8("tolabel"))
        self.frombox = QtGui.QComboBox(self.buyticket_tab)
        self.frombox.setGeometry(QtCore.QRect(240, 110, 101, 21))
        self.frombox.setObjectName(_fromUtf8("frombox"))
        self.frombox.addItem(_fromUtf8(""))
        self.frombox.addItem(_fromUtf8(""))
        self.frombox.addItem(_fromUtf8(""))
        self.frombox.addItem(_fromUtf8(""))
        self.frombox.addItem(_fromUtf8(""))
        self.frombox.addItem(_fromUtf8(""))
        self.frombox.addItem(_fromUtf8(""))
        self.tobox = QtGui.QComboBox(self.buyticket_tab)
        self.tobox.setGeometry(QtCore.QRect(240, 140, 101, 22))
        self.tobox.setObjectName(_fromUtf8("tobox"))
        self.tobox.addItem(_fromUtf8(""))
        self.tobox.addItem(_fromUtf8(""))
        self.tobox.addItem(_fromUtf8(""))
        self.tobox.addItem(_fromUtf8(""))
        self.tobox.addItem(_fromUtf8(""))
        self.tobox.addItem(_fromUtf8(""))
        self.tobox.addItem(_fromUtf8(""))
        self.entertotal = QtGui.QLabel(self.buyticket_tab)
        self.entertotal.setGeometry(QtCore.QRect(130, 190, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entertotal.setFont(font)
        self.entertotal.setObjectName(_fromUtf8("entertotal"))
        self.totalfare = QtGui.QLabel(self.buyticket_tab)
        self.totalfare.setGeometry(QtCore.QRect(240, 190, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.totalfare.setFont(font)
        self.totalfare.setObjectName(_fromUtf8("totalfare"))
        self.buyticketbtn = QtGui.QPushButton(self.buyticket_tab)
        self.buyticketbtn.setGeometry(QtCore.QRect(210, 280, 93, 28))
        self.buyticketbtn.setObjectName(_fromUtf8("buyticketbtn"))
        self.label_2 = QtGui.QLabel(self.buyticket_tab)
        self.label_2.setGeometry(QtCore.QRect(170, 50, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabWidget.addTab(self.buyticket_tab, _fromUtf8(""))
        self.renewtab = QtGui.QWidget()
        self.renewtab.setObjectName(_fromUtf8("renewtab"))
        self.passvalid = QtGui.QLabel(self.renewtab)
        self.passvalid.setGeometry(QtCore.QRect(160, 60, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.passvalid.setFont(font)
        self.passvalid.setObjectName(_fromUtf8("passvalid"))
        self.renewbttn = QtGui.QPushButton(self.renewtab)
        self.renewbttn.setGeometry(QtCore.QRect(200, 240, 93, 28))
        self.renewbttn.setObjectName(_fromUtf8("renewbttn"))
        self.entervalidfrm = QtGui.QLabel(self.renewtab)
        self.entervalidfrm.setGeometry(QtCore.QRect(130, 129, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entervalidfrm.setFont(font)
        self.entervalidfrm.setObjectName(_fromUtf8("entervalidfrm"))
        self.entervalidtill = QtGui.QLabel(self.renewtab)
        self.entervalidtill.setGeometry(QtCore.QRect(130, 170, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entervalidtill.setFont(font)
        self.entervalidtill.setObjectName(_fromUtf8("entervalidtill"))
        self.validfrm = QtGui.QLabel(self.renewtab)
        self.validfrm.setGeometry(QtCore.QRect(260, 130, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.validfrm.setFont(font)
        self.validfrm.setObjectName(_fromUtf8("validfrm"))
        self.validto = QtGui.QLabel(self.renewtab)
        self.validto.setGeometry(QtCore.QRect(260, 170, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.validto.setFont(font)
        self.validto.setObjectName(_fromUtf8("validto"))
        self.tabWidget.addTab(self.renewtab, _fromUtf8(""))
        self.logout_tab = QtGui.QWidget()
        self.logout_tab.setObjectName(_fromUtf8("logout_tab"))
        self.enteroldpsw = QtGui.QLabel(self.logout_tab)
        self.enteroldpsw.setGeometry(QtCore.QRect(110, 130, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enteroldpsw.setFont(font)
        self.enteroldpsw.setObjectName(_fromUtf8("enteroldpsw"))
        self.enternewpsw = QtGui.QLabel(self.logout_tab)
        self.enternewpsw.setGeometry(QtCore.QRect(110, 170, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enternewpsw.setFont(font)
        self.enternewpsw.setObjectName(_fromUtf8("enternewpsw"))
        self.oldpsw = QtGui.QLineEdit(self.logout_tab)
        self.oldpsw.setGeometry(QtCore.QRect(300, 130, 113, 21))
        self.oldpsw.setObjectName(_fromUtf8("oldpsw"))
        self.newpsw = QtGui.QLineEdit(self.logout_tab)
        self.newpsw.setGeometry(QtCore.QRect(300, 160, 113, 22))
        self.newpsw.setObjectName(_fromUtf8("newpsw"))
        self.updatepsw = QtGui.QPushButton(self.logout_tab)
        self.updatepsw.setGeometry(QtCore.QRect(190, 280, 131, 28))
        self.updatepsw.setObjectName(_fromUtf8("updatepsw"))
        self.enter = QtGui.QLabel(self.logout_tab)
        self.enter.setGeometry(QtCore.QRect(140, 40, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.enter.setFont(font)
        self.enter.setObjectName(_fromUtf8("enter"))
        self.entercnfrmpsw = QtGui.QLabel(self.logout_tab)
        self.entercnfrmpsw.setGeometry(QtCore.QRect(110, 210, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entercnfrmpsw.setFont(font)
        self.entercnfrmpsw.setObjectName(_fromUtf8("entercnfrmpsw"))
        self.confirmpsw = QtGui.QLineEdit(self.logout_tab)
        self.confirmpsw.setGeometry(QtCore.QRect(300, 200, 113, 22))
        self.confirmpsw.setObjectName(_fromUtf8("confirmpsw"))
        self.tabWidget.addTab(self.logout_tab, _fromUtf8(""))
        self.aboutustab = QtGui.QWidget()
        self.aboutustab.setObjectName(_fromUtf8("aboutustab"))
        self.textBrowser = QtGui.QTextBrowser(self.aboutustab)
        self.textBrowser.setGeometry(QtCore.QRect(0, -9, 531, 591))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabWidget.addTab(self.aboutustab, _fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 190, 231, 271))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8("Bus-Pass-with-WebCam-Scan-aman-manocha-patch-1/bus_icon.png")))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.entername.setText(_translate("MainWindow", " Name", None))
        self.fname.setText(_translate("MainWindow", "TextLabel", None))
        self.entergen.setText(_translate("MainWindow", "Gender", None))
        self.enterdob.setText(_translate("MainWindow", "D.O.B", None))
        self.enteradd.setText(_translate("MainWindow", "Address", None))
        self.enteradhar.setText(_translate("MainWindow", "Aadhar no.", None))
        self.entermobile.setText(_translate("MainWindow", "Mobile no.", None))
        self.lname.setText(_translate("MainWindow", "TextLabel", None))
        self.gender.setText(_translate("MainWindow", "TextLabel", None))
        self.dob.setText(_translate("MainWindow", "TextLabel", None))
        self.add.setText(_translate("MainWindow", "TextLabel", None))
        self.adhar.setText(_translate("MainWindow", "TextLabel", None))
        self.mobile.setText(_translate("MainWindow", "TextLabel", None))
        self.label.setText(_translate("MainWindow", "WELCOME USER", None))
        self.logout_btn.setText(_translate("MainWindow", "LOGOUT", None))
        self.editdetails_btn.setText(_translate("MainWindow", "EDIT DETAILS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.detailstab), _translate("MainWindow", " DETAILS", None))
        self.fromlabel.setText(_translate("MainWindow", "FROM", None))
        self.tolabel.setText(_translate("MainWindow", "TO", None))
        self.frombox.setItemText(0, _translate("MainWindow", "ROHINI", None))
        self.frombox.setItemText(1, _translate("MainWindow", "PITAMPUA", None))
        self.frombox.setItemText(2, _translate("MainWindow", "NSP", None))
        self.frombox.setItemText(3, _translate("MainWindow", "INDERLOK", None))
        self.frombox.setItemText(4, _translate("MainWindow", "KIRTI NAGAR", None))
        self.frombox.setItemText(5, _translate("MainWindow", "SUBHASH NAGAR", None))
        self.frombox.setItemText(6, _translate("MainWindow", "CP", None))
        self.tobox.setItemText(0, _translate("MainWindow", "ROHINI", None))
        self.tobox.setItemText(1, _translate("MainWindow", "PITAMPURA", None))
        self.tobox.setItemText(2, _translate("MainWindow", "NSP", None))
        self.tobox.setItemText(3, _translate("MainWindow", "INDERLOK", None))
        self.tobox.setItemText(4, _translate("MainWindow", "KIRTI NAGAR", None))
        self.tobox.setItemText(5, _translate("MainWindow", "SUBHASH NAGAR", None))
        self.tobox.setItemText(6, _translate("MainWindow", "CP", None))
        self.entertotal.setText(_translate("MainWindow", "TOTAL FARE", None))
        self.totalfare.setText(_translate("MainWindow", "TextLabel", None))
        self.buyticketbtn.setText(_translate("MainWindow", "Buy Ticket", None))
        self.label_2.setText(_translate("MainWindow", "BUY TICKET", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buyticket_tab), _translate("MainWindow", "BUY TICKET", None))
        self.passvalid.setText(_translate("MainWindow", "PASS VALIDITY", None))
        self.renewbttn.setText(_translate("MainWindow", "Renew", None))
        self.entervalidfrm.setText(_translate("MainWindow", "VALID FROM", None))
        self.entervalidtill.setText(_translate("MainWindow", "VALID TILL", None))
        self.validfrm.setText(_translate("MainWindow", "TextLabel", None))
        self.validto.setText(_translate("MainWindow", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.renewtab), _translate("MainWindow", "RENEW PASS", None))
        self.enteroldpsw.setText(_translate("MainWindow", "OLD PASSWORD", None))
        self.enternewpsw.setText(_translate("MainWindow", "NEW PASSWORD", None))
        self.updatepsw.setText(_translate("MainWindow", "UPDATE PASSWORD", None))
        self.enter.setText(_translate("MainWindow", "ENTER PASSWORD", None))
        self.entercnfrmpsw.setText(_translate("MainWindow", "CONFIRM PASSWORD", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logout_tab), _translate("MainWindow", "CHANGE PASSWORD", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Lato Regular,Arial\'; font-size:14pt; color:#666666;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lato Regular,Arial\'; font-size:14pt; color:#666666; background-color:#ffffff;\">Millions of people travel on buses daily in India. Buses are the most important means of transportation for the common man as these provide the close-to-home connectivity. If you want to know about the buses plying on different routes across Delhi, you can easily search these routes here. We have provided information on almost all the bus routes in Delhi . You are welcome to search the routes you want to travel and click for checking the schedule of various buses for your route.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aboutustab), _translate("MainWindow", "ABOUT US", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

